accounts/urls.py
# from django.urls import path
# from .views import UserRegistrationView, UserLoginView, UserLogoutView,UserLibraryAccountUpdateView
 
# urlpatterns = [
#     path('register/', UserRegistrationView.as_view(), name='register'),
#     path('login/', UserLoginView.as_view(), name='login'),
#     path('logout/', UserLogoutView.as_view(), name='logout'),
#     path('profile/', UserLibraryAccountUpdateView.as_view(), name='profile')
# ]

from django.urls import path
# from . views import *
# from .import views
from . views import (UserRegistrationView, UserLoginView, UserLogoutView, 
            UserProfileUpdateView, UserProfileView,
            password_change,UserPasswordChangeView)

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('update_profile/', UserProfileUpdateView.as_view(), name='update_profile'),
    # path('password_change/', password_change, name='password_change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')
    # path('password_change/', views.password_change, name='password_change'),
]

books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('book_detail/<int:book_id>/', views.book_detail, name='book_detail'),
]

library_management_system/urls.py
# from django.contrib import admin
# from django.urls import path, include
# from core.views import HomeView
# from django.conf import settings
# from django.conf.urls.static import static
# from . import views
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', HomeView.as_view(), name='home'),
#     path('category/<slug:category_slug>/', views.home, name='category_wise_book'),
#     path('accounts/', include('accounts.urls')),
#     path('books/', include('books.urls')),
#     # path('transactions/', include('transactions.urls')),
# ]
# urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', HomeView.as_view(), name='home'),
    # path('books_filter/<slug:book_category>', HomeView.as_view(), name='books_filter'),
    path('', home_view, name='home'),
    path('books_filter/<slug:book_category>', home_view, name='books_filter'),

    # path('books_filter/<path:book_category>/', home_view, name='books_filter'),
    path('accounts/', include('accounts.urls')),
    path('books/', include('books.urls')),
    path('transactions/', include('transactions.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from .constants import GENDER_TYPE

# Create your models here.
class UserLibraryAccount(models.Model):
    user = models.OneToOneField(User, related_name='account', on_delete=models.CASCADE)
    account_no = models.IntegerField(unique=True)
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_TYPE)
    initial_deposite_date = models.DateField(auto_now_add=True)
    balance = models.DecimalField(default=0, max_digits=12, decimal_places=2)

    # def __str__(self):
    #     return str(self.account_no)
    
    def __str__(self):
        return f"{self.user.username} - {self.account_no}"
    
class UserAddress(models.Model):
    user = models.OneToOneField(User, related_name='address', on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length= 100)
    postal_code = models.IntegerField()
    country = models.CharField(max_length=100)
    image = models.ImageField(upload_to='accounts/media/uploads', blank=True, null=True)

    # def __str__(self):
    #     return str(self.user.email)
    
    def __str__(self):
        return f"{self.user.username} - {self.user.email}"
    

transactions/models.py
from django.db import models
from accounts.models import UserLibraryAccount
# Create your models here.
from .constants import TRANSACTION_TYPE

class Transaction(models.Model):
    # ekjon user er multiple transactions hote pare
    account = models.ForeignKey(UserLibraryAccount, related_name = 'transactions', on_delete = models.CASCADE)
    
    amount = models.DecimalField(decimal_places=2, max_digits = 12)
    balance_after_transaction = models.DecimalField(decimal_places=2, max_digits = 12)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null = True)
    timestamp = models.DateTimeField(auto_now_add=True) 
    
    class Meta:
        ordering = ['timestamp'] 

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView
from . forms import UserRegistrationForm, UserUpdateForm
from django.views.generic import RedirectView
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import messages
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from books.models import Book
from transactions.models import Transaction
from transactions.constants import BORROWED, RETURN
from django.contrib.auth import update_session_auth_hash   
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from transactions.views import send_transaction_email
from accounts.models import UserAddress, UserLibraryAccount
# Create your views here.


def send_password_change_email(user, subject, template):
    message = render_to_string(template, {
        'user': user,
    })
    send_email = EmailMultiAlternatives(subject, '', to=[user.email])
    send_email.attach_alternative(message, 'text/html')
    send_email.send()


class UserRegistrationView(FormView):
    template_name = 'accounts/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = form.save()
        print(form.cleaned_data)
        login(self.request, user)
        messages.success(
                self.request, 'Your registration has been successfully!'
        )
        return super().form_valid(form)

    # def form_invalid(self, form):
    #     print(form.errors)
    #     print(form.cleaned_data)
    #     return super().form_invalid(form)


class UserLoginView(LoginView):
    template_name = 'accounts/user_login.html'
    def get_success_url(self):
        return reverse_lazy('profile')
        # return reverse_lazy('home')

    
class UserLogoutView(RedirectView):
    url = reverse_lazy('home')  # Redirect to home after logout

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get(request, *args, **kwargs)

# class UserLogoutView(View):
#     def get(self, request):
#         logout(request)
#         return redirect('home')

class UserProfileUpdateView(LoginRequiredMixin,View):
    template_name = 'accounts/update_profile.html'

    def get(self, request):
        form = UserUpdateForm(instance=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your profile has been updated successfully!'
            )
            return redirect('update_profile')  # Redirect to the user's profile page
        return render(request, self.template_name, {'form': form})

# class UserProfileUpdateView(LoginRequiredMixin,View):
#     template_name = 'accounts/update_profile.html'

#     def get(self, request):
#         form = UserUpdateForm(instance=request.user)
#         # return render(request, 'accounts/profile.html', {'form': form})
#         return render(request, self.template_name, {'form': form})

#     def post(self, request):
#         form = UserUpdateForm(request.POST, instance=request.user)
#         if form.is_valid():
#             form.save()
#             messages.success(
#                 self.request, 'Your profile has been updated successfully!!!')
#             return redirect('update_profile')
#         else:
#             print(form.errors)
#         return render(request, self.template_name, {'form': form})

#################################################################################
    
# from accounts.models import UserAddress, UserLibraryAccount
# class UserProfileView(LoginRequiredMixin, View):
#     template_name = 'accounts/profile.html'
#     def get(self, request):
#         user_address = UserAddress.objects.filter(user=request.user).first()
#         print(user_address.country, user_address.image)
        
#         # user_address = UserAddress.objects.filter(user_id=request.user)
#         # for i in user_address:
#         #     print(i.country, i.user, i.city, i.street_address,i.postal_code, i.image)
          
#         # user_bank_account = UserLibraryAccount.objects.filter(user_id =request.user)
#         # for i in user_bank_account:
#         #     print(i.user, i.account_no, i.account_type, i.balance, i.birth_date, i.gender, i.initial_deposite_date)
#         return render(request, self.template_name,{'user_address':user_address})
    


class UserProfileView(LoginRequiredMixin, View):
    template_name = 'accounts/profile.html'
    
    def get(self, request):

        user_address = UserAddress.objects.filter(user=request.user).first()
        # print(user_address.country, user_address.image)
        
        # user_address = UserAddress.objects.filter(user_id=request.user)
        # for i in user_address:
        #     print(i.country, i.user, i.city, i.street_address,i.postal_code, i.image)
          
        # user_bank_account = UserLibraryAccount.objects.filter(user_id =request.user)
        # for i in user_bank_account:
        #     print(i.user, i.account_no, i.account_type, i.balance, i.birth_date, i.gender, i.initial_deposite_date)
    



        borrowed_books = Book.objects.filter(borrowers=request.user)
        # for book in borrowed_books:
        #     print(book.title, book.price, book.categories)

        # all_transactions = Transaction.objects.filter(account=request.user.account).order_by('-timestamp')
        # for transaction in all_transactions:
        #     print(transaction.amount, transaction.balance_after_transaction,transaction.transaction_type)

        # Create a list to store book details along with their borrowing history
        borrowed_books_details = []

        for book in borrowed_books:
            # Get the borrowing history for each book
            details = Transaction.objects.filter(
                account=request.user.account, 
                amount=book.price,
            ).order_by('-timestamp')

            # Add book and its history to the list
            borrowed_books_details.append({'book': book, 'details': details})

            # Extract transaction details for each book
            # transactions_for_book = [{'amount': transaction.amount, 'balance_after_transaction': transaction.balance_after_transaction}
            #                 for transaction in borrowed_books_details]
            
        context = {
            'user': request.user,
            'user_address': user_address,
            # 'borrowed_books': borrowed_books,
            'borrowed_books_details': borrowed_books_details,
            # 'all_transactions': all_transactions,
        }
        return render(request, self.template_name, context=context)
        # return render(request, self.template_name, context)
###########################################################################
@login_required
def password_change(request):
    if request.user.is_authenticated:
        form = PasswordChangeForm(request.user)
        if request.method == 'POST':
            form = PasswordChangeForm(request.user, request.POST)
            if form.is_valid():
                user = form.save()
                update_session_auth_hash(request, user)
                messages.success(
                    request, 'Your password was successfully updated!')
                
                send_password_change_email(
                    request.user, 
                    'Password Changed',
                    'accounts/password_change_mail.html'
                    )
                return redirect('profile')
            else:
                messages.error(request, 'Please correct the error below.')
        return render(request, 'accounts/password_change_form.html', {'form': form, 'title': 'Change Your Password'})
    else:
        return redirect('home')
    
#................................................................................
# from django.contrib.auth import update_session_auth_hash   
# from django.contrib.auth.forms import PasswordChangeForm
# from django.contrib.auth.views import PasswordChangeView
# from transactions.views import send_transaction_email
class UserPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    form_class = PasswordChangeForm
    # success_url = reverse_lazy('password_change')
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request, 'Your password was successfully updated!'
        )
                
        # Updating the password logs out all other sessions for the user
        # except the current one.
        update_session_auth_hash(self.request, form.user)
        send_transaction_email(
                    self.request.user,
                    '' ,
                    'Password Changed',
                    'accounts/password_change_mail.html'
                    )
        return super().form_valid(form)
    
    

accounts/templates/accounts/password_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{title}}{% endblock %}
{% block content %}

<div class="w-full flex mt-3 mb-24 justify-center">
    <div class="bg-white w-5/12 rounded-lg">
        <div class="text-center">
            <h2 class="font-bold mb-4 mt-2 text-2xl text-black">Change Your Password</h2>
        </div>

        <form method="post" class="shadow-2xl px-10 py-5 mx-10 mb-5">
            {% csrf_token %}
            {% comment %} {% if form.errors %}
            <div class="text-red-500 text-sm mb-4">
                {{ form.errors }}
            </div>
            {% endif %}  {% endcomment %}

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="id_old_password">
                    Old Password
                </label>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline"
                    name="old_password" id="old_password" type="password" required placeholder="Old Password">
                
                {% if form.old_password.errors %}
                <p class="text-red-500 text-xs italic">{{ form.old_password.errors.0 }}</p>
                {% endif %}
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="id_new_password1">
                    New password:
                </label>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline"
                    name="new_password1" id="new_password1" type="password" required placeholder="New Password">
                {% if form.new_password1.errors %}
                <p class="text-red-500 text-xs italic">{{ form.new_password1.errors.0 }}</p>
                {% endif %}
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="id_new_password2">
                    New password:
                </label>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline"
                    name="new_password2" id="new_password2" type="password" required placeholder="Confirm New Password">

                    {% if form.new_password2.errors %}
                    <p class="text-red-500 text-xs italic">{{ form.new_password2.errors.0 }}</p>
                    {% endif %}
            </div>

            <div class="flex w-full justify-center">
                <button
                    class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg"
                    type="submit">
                    Submit
                </button>
            </div>
        </form>

{% endblock %}

accounts/templates/accounts/password_change_mail.html
<p>Hi {{ user.first_name }} {{ user.last_name }},</p>
<p>Your password has been changed successfully. If you did not make this change, please contact us immediately.</p>
<p>Thank you for using our service.</p>
<p>Regards,</p>
<p>Laibrary Management System</p>

accounts/templates/accounts/profile.html
{% extends 'base.html' %} {% load static %} {% block head_title %}Laibrary System{% endblock %} {% block content %} 

<!-- https://gist.github.com/goodreds/5b8a4a2bf11ff67557d38c5e727ea86c -->

<div
    class="max-w-2xl mx-4 sm:max-w-sm md:max-w-sm lg:max-w-sm xl:max-w-sm sm:mx-auto md:mx-auto lg:mx-auto xl:mx-auto mt-16 bg-white shadow-xl rounded-lg text-gray-900">
    <div class="rounded-t-lg h-32 overflow-hidden">
        <img class="object-cover object-top w-full" src='https://images.unsplash.com/photo-1549880338-65ddcdfd017b?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt='Mountain'>
    </div>
    <div class="mx-auto w-32 h-32 relative -mt-16 border-4 border-white rounded-full overflow-hidden">
        <img class="object-cover object-center h-32" src='{{ user_address.image.url }}'>
    </div>
    <div class="text-center mt-2">
        <h2 class="font-semibold">{{ request.user.first_name }} {{ request.user.last_name }}</h2>
        <p class="text-gray-500">{{ request.user.username }}</p>
    </div>
    <ul class="py-4 mt-2 text-gray-700 flex items-center justify-around">
        <li class="flex flex-col items-center justify-around">
            <svg class="w-4 fill-current text-blue-900" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path
                    d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z" />
            </svg>
            <div>2k</div>
        </li>
        <li class="flex flex-col items-center justify-between">
            <svg class="w-4 fill-current text-blue-900" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path
                    d="M7 8a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm0 1c2.15 0 4.2.4 6.1 1.09L12 16h-1.25L10 20H4l-.75-4H2L.9 10.09A17.93 17.93 0 0 1 7 9zm8.31.17c1.32.18 2.59.48 3.8.92L18 16h-1.25L16 20h-3.96l.37-2h1.25l1.65-8.83zM13 0a4 4 0 1 1-1.33 7.76 5.96 5.96 0 0 0 0-7.52C12.1.1 12.53 0 13 0z" />
            </svg>
            <div>10k</div>
        </li>
        <li class="flex flex-col items-center justify-around">
            <svg class="w-4 fill-current text-blue-900" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path
                    d="M9 12H1v6a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-6h-8v2H9v-2zm0-1H0V5c0-1.1.9-2 2-2h4V2a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v1h4a2 2 0 0 1 2 2v6h-9V9H9v2zm3-8V2H8v1h4z" />
            </svg>
            <div>15</div>
        </li>
    </ul>
    <div class="p-4 border-t mx-8 mt-2">
        <button class="w-1/2 block mx-auto rounded-full bg-gray-900 hover:shadow-lg font-semibold text-white px-6 py-2">Follow</button>
    </div>
</div>




<div class="bg-white pb-12 mt-5 px-4">
    <div class="flex items-center justify-between ">
        <h4 class="font-bold text-3xl text-left pb-5">Account No: {{request.user.account.account_no}}</h4>
        <a href="{% url 'update_profile' %}"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            Update Profile
        </a>
        <a href="{% url 'password_change' %}"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            Change Password
        </a>
    </div>

    <div class="my-8">
        {% if borrowed_books_details %}
        <h2 class="text-2xl font-bold mb-4">Borrowed Books List:</h2>
        <table class="border-collapse border border-blue-100">
            <thead>
                <tr>
                    <th class="border border-blue-300">ID</th>
                    <th class="border border-blue-300">Title</th>
                    <th class="border border-blue-300">Acion</th>
                    <th class="border border-blue-300">Price</th>
                    <th class="border border-blue-300">Date</th>
                    <th class="border border-blue-300">Balance After Transaction</th>
                    <th class="border border-blue-300">Transaction Type</th>
                </tr>
            </thead>
            <tbody class="text-center">
                {% for h in borrowed_books_details %}
                <tr>
                    <td class="border border-blue-400 px-4 py-2">{{ h.book.id }}</td>
                    <td class="border border-blue-400 px-4 py-2">
                        <a href="{% url 'book_detail' h.book.id %}" class="text-blue-500 hover:text-blue-700">{{ h.book.title }}</a>
                    </td>
                    <td class="border border-blue-400 px-4 py-2">
                        <a href="{% url 'book_detail' h.book.id %}" class="text-blue-500 hover:text-blue-700">Return the book</a>
                    </td>
                    <td class="border border-blue-400 px-4 py-2">${{ h.book.price }}</td>
                    <td class="border border-blue-400 px-4 py-2">
                        <ul>
                            {% for transaction in h.details %}
                            <li>
                                {{ transaction.timestamp }}
                            </li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td class="border border-blue-400 px-4 py-2">
                        <ul>
                            {% for transaction in h.details %}
                            <li>
                                {{ transaction.balance_after_transaction }}
                            </li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td class="border border-blue-400 px-4 py-2">
                        <ul>
                            {% for transaction in h.details %}
                            <li class="font-sans font-black">
                                {{ transaction.get_transaction_type_display }}
                            </li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h1 class="text-2xl font-bold text-center">No books borrowed.</h1>
        {% endif %}

    </div>   
</div>
{% include "footer.html" %}
{% endblock %}
                                    

accounts/templates/accounts/user_login.html
{% extends 'base.html' %}  {% block content %} {% if form.non_field_errors %} {% for error in form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %} {% endif %}
<div class="grid grid-cols-3 gap-4">
    <div></div>
    <div class="py-2 px-3 rounded-xl bg-white mt-10 mb-24">
        <h1 class="font-bold text-3xl text-center pb-5 shadow-md">Login</h1>
        <div class="w-full mt-10">
            <form method="post" class="shadow-md border border-gray-200 rounded px-8 pt-6 pb-8 mb-4">
                {% csrf_token %} {% for hidden_field in form.hidden_fields %} {{ hidden_field.errors }} {{ hidden_field }} {% endfor %} 
                {% for field in form.visible_fields %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                {{ field.label }}
            </label>
                    <input class="shadow appearance-none border border-gray-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="{{ field.name }}" id="{{ field.id_for_label }}" type="{{ field.widget_type }}">
                </div>
                {% if field.errors %} {% for error in field.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                {% endfor %} {% endif %} {% endfor %}

                <div class="flex items-center justify-center w-full">
                    <button class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                Log In
            </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}